// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddProject(arg1, arg2) {
  return window['go']['handlers']['App']['AddProject'](arg1, arg2);
}

export function BuildProject(arg1, arg2) {
  return window['go']['handlers']['App']['BuildProject'](arg1, arg2);
}

export function CancelBuild(arg1) {
  return window['go']['handlers']['App']['CancelBuild'](arg1);
}

export function CheckIfHugoProject(arg1, arg2) {
  return window['go']['handlers']['App']['CheckIfHugoProject'](arg1, arg2);
}

export function CloneGitHubRepository(arg1, arg2) {
  return window['go']['handlers']['App']['CloneGitHubRepository'](arg1, arg2);
}

export function CloneProject(arg1, arg2) {
  return window['go']['handlers']['App']['CloneProject'](arg1, arg2);
}

export function CommitChanges(arg1, arg2) {
  return window['go']['handlers']['App']['CommitChanges'](arg1, arg2);
}

export function ConvertConfigFormat(arg1, arg2) {
  return window['go']['handlers']['App']['ConvertConfigFormat'](arg1, arg2);
}

export function CopyFile(arg1, arg2, arg3) {
  return window['go']['handlers']['App']['CopyFile'](arg1, arg2, arg3);
}

export function CopyFileFromExternal(arg1, arg2, arg3) {
  return window['go']['handlers']['App']['CopyFileFromExternal'](arg1, arg2, arg3);
}

export function CreateContent(arg1, arg2) {
  return window['go']['handlers']['App']['CreateContent'](arg1, arg2);
}

export function CreateDeployment(arg1, arg2, arg3) {
  return window['go']['handlers']['App']['CreateDeployment'](arg1, arg2, arg3);
}

export function CreateDirectory(arg1, arg2) {
  return window['go']['handlers']['App']['CreateDirectory'](arg1, arg2);
}

export function CreateFile(arg1, arg2, arg3) {
  return window['go']['handlers']['App']['CreateFile'](arg1, arg2, arg3);
}

export function CreateGitHubRepository(arg1, arg2, arg3) {
  return window['go']['handlers']['App']['CreateGitHubRepository'](arg1, arg2, arg3);
}

export function CreateNewProject(arg1, arg2) {
  return window['go']['handlers']['App']['CreateNewProject'](arg1, arg2);
}

export function CreateProjectGroup(arg1, arg2, arg3) {
  return window['go']['handlers']['App']['CreateProjectGroup'](arg1, arg2, arg3);
}

export function CreateProjectTemplate(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['App']['CreateProjectTemplate'](arg1, arg2, arg3, arg4);
}

export function DeleteContent(arg1, arg2) {
  return window['go']['handlers']['App']['DeleteContent'](arg1, arg2);
}

export function DeleteDeployment(arg1) {
  return window['go']['handlers']['App']['DeleteDeployment'](arg1);
}

export function DeleteFile(arg1, arg2) {
  return window['go']['handlers']['App']['DeleteFile'](arg1, arg2);
}

export function DeleteProjectGroup(arg1) {
  return window['go']['handlers']['App']['DeleteProjectGroup'](arg1);
}

export function DeleteProjectTemplate(arg1) {
  return window['go']['handlers']['App']['DeleteProjectTemplate'](arg1);
}

export function Deploy(arg1, arg2) {
  return window['go']['handlers']['App']['Deploy'](arg1, arg2);
}

export function ExecuteBulkOperation(arg1, arg2, arg3) {
  return window['go']['handlers']['App']['ExecuteBulkOperation'](arg1, arg2, arg3);
}

export function GetAllProjectGroups() {
  return window['go']['handlers']['App']['GetAllProjectGroups']();
}

export function GetAllProjectTemplates() {
  return window['go']['handlers']['App']['GetAllProjectTemplates']();
}

export function GetArchetype(arg1, arg2) {
  return window['go']['handlers']['App']['GetArchetype'](arg1, arg2);
}

export function GetAvailableEnvironments(arg1) {
  return window['go']['handlers']['App']['GetAvailableEnvironments'](arg1);
}

export function GetBranches(arg1) {
  return window['go']['handlers']['App']['GetBranches'](arg1);
}

export function GetBuildHistory(arg1, arg2) {
  return window['go']['handlers']['App']['GetBuildHistory'](arg1, arg2);
}

export function GetBuildLogs(arg1, arg2) {
  return window['go']['handlers']['App']['GetBuildLogs'](arg1, arg2);
}

export function GetBuildStatus(arg1) {
  return window['go']['handlers']['App']['GetBuildStatus'](arg1);
}

export function GetBulkOperation(arg1) {
  return window['go']['handlers']['App']['GetBulkOperation'](arg1);
}

export function GetCommitHistory(arg1, arg2) {
  return window['go']['handlers']['App']['GetCommitHistory'](arg1, arg2);
}

export function GetConfig(arg1, arg2) {
  return window['go']['handlers']['App']['GetConfig'](arg1, arg2);
}

export function GetConfigFileInfo(arg1) {
  return window['go']['handlers']['App']['GetConfigFileInfo'](arg1);
}

export function GetContent(arg1, arg2) {
  return window['go']['handlers']['App']['GetContent'](arg1, arg2);
}

export function GetDeployment(arg1) {
  return window['go']['handlers']['App']['GetDeployment'](arg1);
}

export function GetDeploymentHistory(arg1, arg2) {
  return window['go']['handlers']['App']['GetDeploymentHistory'](arg1, arg2);
}

export function GetDeploymentsForProject(arg1) {
  return window['go']['handlers']['App']['GetDeploymentsForProject'](arg1);
}

export function GetEditableRegions(arg1, arg2) {
  return window['go']['handlers']['App']['GetEditableRegions'](arg1, arg2);
}

export function GetGitConfig(arg1) {
  return window['go']['handlers']['App']['GetGitConfig'](arg1);
}

export function GetGitHubRepositories() {
  return window['go']['handlers']['App']['GetGitHubRepositories']();
}

export function GetGitHubUser() {
  return window['go']['handlers']['App']['GetGitHubUser']();
}

export function GetGitStatus(arg1) {
  return window['go']['handlers']['App']['GetGitStatus'](arg1);
}

export function GetHugoVersion() {
  return window['go']['handlers']['App']['GetHugoVersion']();
}

export function GetInstalledThemes(arg1) {
  return window['go']['handlers']['App']['GetInstalledThemes'](arg1);
}

export function GetPageStructure(arg1, arg2) {
  return window['go']['handlers']['App']['GetPageStructure'](arg1, arg2);
}

export function GetProject(arg1) {
  return window['go']['handlers']['App']['GetProject'](arg1);
}

export function GetProjectGroup(arg1) {
  return window['go']['handlers']['App']['GetProjectGroup'](arg1);
}

export function GetProjectStructure(arg1, arg2) {
  return window['go']['handlers']['App']['GetProjectStructure'](arg1, arg2);
}

export function GetProjectTemplate(arg1) {
  return window['go']['handlers']['App']['GetProjectTemplate'](arg1);
}

export function GetProjects() {
  return window['go']['handlers']['App']['GetProjects']();
}

export function GetServerLogs(arg1, arg2) {
  return window['go']['handlers']['App']['GetServerLogs'](arg1, arg2);
}

export function GetServerStatus(arg1) {
  return window['go']['handlers']['App']['GetServerStatus'](arg1);
}

export function GetSiteStructure(arg1) {
  return window['go']['handlers']['App']['GetSiteStructure'](arg1);
}

export function GetThemeFromMarketplace(arg1) {
  return window['go']['handlers']['App']['GetThemeFromMarketplace'](arg1);
}

export function GetThemeIndex() {
  return window['go']['handlers']['App']['GetThemeIndex']();
}

export function GetThemeInstallStatus(arg1) {
  return window['go']['handlers']['App']['GetThemeInstallStatus'](arg1);
}

export function GetThemeMetadata(arg1) {
  return window['go']['handlers']['App']['GetThemeMetadata'](arg1);
}

export function GetVisualEditingConfig(arg1) {
  return window['go']['handlers']['App']['GetVisualEditingConfig'](arg1);
}

export function GetWatchStatus(arg1) {
  return window['go']['handlers']['App']['GetWatchStatus'](arg1);
}

export function InitializeGitRepository(arg1) {
  return window['go']['handlers']['App']['InitializeGitRepository'](arg1);
}

export function InstallTheme(arg1, arg2) {
  return window['go']['handlers']['App']['InstallTheme'](arg1, arg2);
}

export function InstallThemeSubmodule(arg1, arg2, arg3) {
  return window['go']['handlers']['App']['InstallThemeSubmodule'](arg1, arg2, arg3);
}

export function IsHugoInstalled() {
  return window['go']['handlers']['App']['IsHugoInstalled']();
}

export function LinkProjectToGitHub(arg1, arg2) {
  return window['go']['handlers']['App']['LinkProjectToGitHub'](arg1, arg2);
}

export function ListArchetypes(arg1) {
  return window['go']['handlers']['App']['ListArchetypes'](arg1);
}

export function ListContent(arg1, arg2) {
  return window['go']['handlers']['App']['ListContent'](arg1, arg2);
}

export function OpenFileDialog(arg1, arg2) {
  return window['go']['handlers']['App']['OpenFileDialog'](arg1, arg2);
}

export function OpenInFileExplorer(arg1) {
  return window['go']['handlers']['App']['OpenInFileExplorer'](arg1);
}

export function OpenMultipleFilesDialog(arg1, arg2) {
  return window['go']['handlers']['App']['OpenMultipleFilesDialog'](arg1, arg2);
}

export function PullFromGitHub(arg1, arg2, arg3) {
  return window['go']['handlers']['App']['PullFromGitHub'](arg1, arg2, arg3);
}

export function PushToGitHub(arg1, arg2, arg3) {
  return window['go']['handlers']['App']['PushToGitHub'](arg1, arg2, arg3);
}

export function ReadFile(arg1, arg2) {
  return window['go']['handlers']['App']['ReadFile'](arg1, arg2);
}

export function ReadFileAsBase64(arg1, arg2) {
  return window['go']['handlers']['App']['ReadFileAsBase64'](arg1, arg2);
}

export function RefreshProject(arg1) {
  return window['go']['handlers']['App']['RefreshProject'](arg1);
}

export function RemoveProject(arg1) {
  return window['go']['handlers']['App']['RemoveProject'](arg1);
}

export function RemoveTheme(arg1, arg2) {
  return window['go']['handlers']['App']['RemoveTheme'](arg1, arg2);
}

export function RenameFile(arg1, arg2, arg3) {
  return window['go']['handlers']['App']['RenameFile'](arg1, arg2, arg3);
}

export function ScanDirectory(arg1) {
  return window['go']['handlers']['App']['ScanDirectory'](arg1);
}

export function SearchGitHubRepositories(arg1, arg2) {
  return window['go']['handlers']['App']['SearchGitHubRepositories'](arg1, arg2);
}

export function SearchGitHubThemes(arg1, arg2) {
  return window['go']['handlers']['App']['SearchGitHubThemes'](arg1, arg2);
}

export function SearchHugoProjects(arg1, arg2) {
  return window['go']['handlers']['App']['SearchHugoProjects'](arg1, arg2);
}

export function SearchThemes(arg1, arg2) {
  return window['go']['handlers']['App']['SearchThemes'](arg1, arg2);
}

export function SelectDirectory(arg1) {
  return window['go']['handlers']['App']['SelectDirectory'](arg1);
}

export function SetAutoRebuild(arg1, arg2) {
  return window['go']['handlers']['App']['SetAutoRebuild'](arg1, arg2);
}

export function SetGitHubToken(arg1) {
  return window['go']['handlers']['App']['SetGitHubToken'](arg1);
}

export function SetVisualEditingEnabled(arg1, arg2) {
  return window['go']['handlers']['App']['SetVisualEditingEnabled'](arg1, arg2);
}

export function StageFiles(arg1, arg2) {
  return window['go']['handlers']['App']['StageFiles'](arg1, arg2);
}

export function StartServer(arg1, arg2) {
  return window['go']['handlers']['App']['StartServer'](arg1, arg2);
}

export function StopServer(arg1) {
  return window['go']['handlers']['App']['StopServer'](arg1);
}

export function StopWatching(arg1) {
  return window['go']['handlers']['App']['StopWatching'](arg1);
}

export function UpdateConfig(arg1, arg2, arg3) {
  return window['go']['handlers']['App']['UpdateConfig'](arg1, arg2, arg3);
}

export function UpdateContent(arg1, arg2, arg3) {
  return window['go']['handlers']['App']['UpdateContent'](arg1, arg2, arg3);
}

export function UpdateDeployment(arg1, arg2) {
  return window['go']['handlers']['App']['UpdateDeployment'](arg1, arg2);
}

export function UpdatePageField(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['App']['UpdatePageField'](arg1, arg2, arg3, arg4);
}

export function UpdateProjectGroup(arg1, arg2, arg3, arg4) {
  return window['go']['handlers']['App']['UpdateProjectGroup'](arg1, arg2, arg3, arg4);
}

export function UpdateTheme(arg1, arg2) {
  return window['go']['handlers']['App']['UpdateTheme'](arg1, arg2);
}

export function UpdateThemeIndex() {
  return window['go']['handlers']['App']['UpdateThemeIndex']();
}

export function UpdateVisualEditingConfig(arg1, arg2) {
  return window['go']['handlers']['App']['UpdateVisualEditingConfig'](arg1, arg2);
}

export function ValidateConfig(arg1, arg2) {
  return window['go']['handlers']['App']['ValidateConfig'](arg1, arg2);
}

export function ValidateProject(arg1) {
  return window['go']['handlers']['App']['ValidateProject'](arg1);
}

export function WatchProject(arg1, arg2) {
  return window['go']['handlers']['App']['WatchProject'](arg1, arg2);
}

export function WriteFile(arg1, arg2, arg3) {
  return window['go']['handlers']['App']['WriteFile'](arg1, arg2, arg3);
}
