// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';
import {services} from '../models';

export function AddProject(arg1:string,arg2:string):Promise<models.Project>;

export function BuildProject(arg1:string,arg2:models.BuildOptions):Promise<models.Build>;

export function CancelBuild(arg1:string):Promise<void>;

export function CloneProject(arg1:string,arg2:models.CloneOptions):Promise<models.Project>;

export function ConvertConfigFormat(arg1:string,arg2:string):Promise<void>;

export function CopyFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateContent(arg1:string,arg2:models.ContentOptions):Promise<models.Content>;

export function CreateDeployment(arg1:string,arg2:string,arg3:Record<string, any>):Promise<models.Deployment>;

export function CreateDirectory(arg1:string,arg2:string):Promise<void>;

export function CreateFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function CreateNewProject(arg1:string,arg2:string):Promise<models.Project>;

export function CreateProjectGroup(arg1:string,arg2:string,arg3:Array<string>):Promise<models.ProjectGroup>;

export function CreateProjectTemplate(arg1:string,arg2:string,arg3:Record<string, any>,arg4:Array<models.TemplateFile>):Promise<models.ProjectTemplate>;

export function DeleteContent(arg1:string,arg2:string):Promise<void>;

export function DeleteDeployment(arg1:string):Promise<void>;

export function DeleteFile(arg1:string,arg2:string):Promise<void>;

export function DeleteProjectGroup(arg1:string):Promise<void>;

export function DeleteProjectTemplate(arg1:string):Promise<void>;

export function Deploy(arg1:string,arg2:models.DeploymentOptions):Promise<models.DeploymentHistory>;

export function ExecuteBulkOperation(arg1:string,arg2:Array<string>,arg3:Record<string, any>):Promise<models.BulkOperation>;

export function GetAllProjectGroups():Promise<Array<models.ProjectGroup>>;

export function GetAllProjectTemplates():Promise<Array<models.ProjectTemplate>>;

export function GetArchetype(arg1:string,arg2:string):Promise<models.Archetype>;

export function GetAvailableEnvironments(arg1:string):Promise<Array<string>>;

export function GetBuildHistory(arg1:string,arg2:number):Promise<Array<models.Build>>;

export function GetBuildLogs(arg1:string,arg2:number):Promise<Array<string>>;

export function GetBuildStatus(arg1:string):Promise<services.BuildStatusResponse>;

export function GetBulkOperation(arg1:string):Promise<models.BulkOperation>;

export function GetConfig(arg1:string,arg2:string):Promise<Record<string, any>>;

export function GetConfigFileInfo(arg1:string):Promise<models.ConfigFileInfo>;

export function GetContent(arg1:string,arg2:string):Promise<models.Content>;

export function GetDeployment(arg1:string):Promise<models.Deployment>;

export function GetDeploymentHistory(arg1:string,arg2:number):Promise<Array<models.DeploymentHistory>>;

export function GetDeploymentsForProject(arg1:string):Promise<Array<models.Deployment>>;

export function GetEditableRegions(arg1:string,arg2:string):Promise<Array<models.EditableRegion>>;

export function GetHugoVersion():Promise<string>;

export function GetInstalledThemes(arg1:string):Promise<Array<models.Theme>>;

export function GetPageStructure(arg1:string,arg2:string):Promise<models.PageStructure>;

export function GetProject(arg1:string):Promise<models.Project>;

export function GetProjectGroup(arg1:string):Promise<models.ProjectGroup>;

export function GetProjectStructure(arg1:string,arg2:string):Promise<Array<models.FileInfo>>;

export function GetProjectTemplate(arg1:string):Promise<models.ProjectTemplate>;

export function GetProjects():Promise<Array<models.Project>>;

export function GetServerLogs(arg1:string,arg2:number):Promise<Array<string>>;

export function GetServerStatus(arg1:string):Promise<models.ServerInfo>;

export function GetSiteStructure(arg1:string):Promise<models.SiteStructure>;

export function GetThemeFromMarketplace(arg1:string):Promise<models.Theme>;

export function GetThemeIndex():Promise<Array<models.Theme>>;

export function GetThemeMetadata(arg1:string):Promise<models.ThemeMetadata>;

export function GetVisualEditingConfig(arg1:string):Promise<models.VisualEditingConfig>;

export function GetWatchStatus(arg1:string):Promise<boolean>;

export function InstallTheme(arg1:string,arg2:string):Promise<void>;

export function InstallThemeSubmodule(arg1:string,arg2:string,arg3:string):Promise<void>;

export function IsHugoInstalled():Promise<boolean>;

export function ListArchetypes(arg1:string):Promise<Array<models.Archetype>>;

export function ListContent(arg1:string,arg2:string):Promise<models.ContentList>;

export function OpenInFileExplorer(arg1:string):Promise<void>;

export function ReadFile(arg1:string,arg2:string):Promise<string>;

export function RefreshProject(arg1:string):Promise<models.Project>;

export function RemoveProject(arg1:string):Promise<void>;

export function RemoveTheme(arg1:string,arg2:string):Promise<void>;

export function RenameFile(arg1:string,arg2:string,arg3:string):Promise<void>;

export function ScanDirectory(arg1:string):Promise<Array<models.Project>>;

export function SearchGitHubThemes(arg1:string,arg2:number):Promise<Array<models.Theme>>;

export function SearchThemes(arg1:string,arg2:Record<string, any>):Promise<Array<models.Theme>>;

export function SelectDirectory(arg1:string):Promise<string>;

export function SetAutoRebuild(arg1:string,arg2:boolean):Promise<void>;

export function SetGitHubToken(arg1:string):Promise<void>;

export function SetVisualEditingEnabled(arg1:string,arg2:boolean):Promise<void>;

export function StartServer(arg1:string,arg2:models.ServerOptions):Promise<models.ServerInfo>;

export function StopServer(arg1:string):Promise<void>;

export function StopWatching(arg1:string):Promise<void>;

export function UpdateConfig(arg1:string,arg2:Array<string>,arg3:any):Promise<void>;

export function UpdateContent(arg1:string,arg2:string,arg3:models.ContentOptions):Promise<models.Content>;

export function UpdateDeployment(arg1:string,arg2:Record<string, any>):Promise<models.Deployment>;

export function UpdatePageField(arg1:string,arg2:string,arg3:string,arg4:any):Promise<void>;

export function UpdateProjectGroup(arg1:string,arg2:string,arg3:string,arg4:Array<string>):Promise<models.ProjectGroup>;

export function UpdateTheme(arg1:string,arg2:string):Promise<void>;

export function UpdateThemeIndex():Promise<void>;

export function UpdateVisualEditingConfig(arg1:string,arg2:models.VisualEditingConfig):Promise<void>;

export function ValidateConfig(arg1:Array<string>,arg2:any):Promise<void>;

export function ValidateProject(arg1:string):Promise<boolean>;

export function WatchProject(arg1:string,arg2:boolean):Promise<void>;

export function WriteFile(arg1:string,arg2:string,arg3:string):Promise<void>;
